[package]
name = "day4"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
strum = "0.26"
strum_macros = "0.26"
