[package]
name = "day5"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
async-trait = "0.1.59"
tokio = { version ="1.22", features = ["full"] }